steps:
# 1. Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'us-west2-docker.pkg.dev/$PROJECT_ID/underpin-notifications-cron-image/underpin-notifications-cron-image:$_COMMIT_SHA'
    - '.'

# 2. Push the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'us-west2-docker.pkg.dev/$PROJECT_ID/underpin-notifications-cron-image/underpin-notifications-cron-image:$_COMMIT_SHA'

# 3. Create or Update the Cloud Run Job definition
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'jobs'
    - 'replace'
    # Use a user-defined variable for the Job Name
    - '$_JOB_NAME' 
    - '--image'
    - 'us-west2-docker.pkg.dev/$PROJECT_ID/underpin-notifications-cron-image/underpin-notifications-cron-image:$_COMMIT_SHA'
    - '--task-timeout'
    - '60s'
    - '--region'
    # Use a user-defined variable for the Region
    - '$_REGION' 

images:
- 'us-west2-docker.pkg.dev/$PROJECT_ID/underpin-notifications-cron-image/underpin-notifications-cron-image:$_COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY